### ISSUE TITLE
`torchgeo==0.5` causes major errors due to renamed arg

### ISSUE THREAD

**Issue by Pale-Blue-Dot-97** [Pale-Blue-Dot-97/Minerva#269]
**Describe the bug**
The latest version of `torchgeo` (v0.5) makes breaking changes that affect this package. Namely, the renaming of the `root` arg for `GeoDataset` to `paths`. The only explicit point that `root` is referred to in `minerva` is in `datasets.factory.create_subdataset`.

**To Reproduce**
1. Ensure your environment includes `torchgeo==0.5`
2. Run `pytest tests/test_factory.py` (errors will occur in the setup of any test due to a fixture breaking too).
3. Tests will fail due to this bug.

**Expected behavior**
Tests pass.

**Environment (please complete the following information):**
 - `torchgeo==0.5`

**Comment by calebrob6** [comment]
Hey Harry, I'll try to remember to ping you directly in the discussion before the next torchgeo release so we can double check that backwards incompatible changes aren't messing you up too badly!

**Comment by Pale-Blue-Dot-97** [comment]
Hi Caleb, no problem! It only affected two lines of code but those two lines were in a function at the core of the package's functionality, hence causing most tests to fail. Was easy to debug and fix. And the new `paths` argument will be quite useful over the old `root` so worth the breakages! 😊
